version: "3.7"

services:
    php:
        build:
            context: ./
        volumes:
            - .:/var/www/html/
        depends_on:
            - db

    nginx:
        image: bitnami/nginx:1.19-debian-10
        ports:
            - 8383:8080
        volumes:
            - ./distrib/app.conf:/opt/bitnami/nginx/conf/server_blocks/app.conf
            - .:/var/www/html/
        depends_on:
            - php
    db:
        # be careful to have the same version as ./config/package/doctrine.yml
        image: postgres:11.9
        environment:
            - POSTGRES_DB=bookmark
            - POSTGRES_USER=bookmark # Pour le dev
            - POSTGRES_PASSWORD=password # Pour le dev
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - 5434:5432

volumes:
    db-data: {}
